version: '3'
services:
  mongodb:
    image: mongo:3.6
    container_name: "expresscart-mongodb"
    volumes:
      - expresscart-mongo-data:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
    restart: always

  expresscart:
    image: "node:16.13.0"
    build: .
    container_name: "expresscart"
    environment:
      NODE_ENV: development
      NODE_PATH: /
    ports:
      - "1111:1111"
    links:
      - mongodb
    depends_on:
      - mongodb
    restart: always

volumes:
  expresscart-mongo-data:
  uploads: